export type Tool = {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  type?: "name" | "copy" | "template" | "checklist" | "calculator";
  fields?: { label: string; placeholder: string }[];
};

export const TOOLS: Record<string, Tool> = {
  "rice-calculator": {
    slug: "rice-calculator",
    name: "RICE Score Calculator",
    tagline: "Prioritize your backlog in minutes",
    description:
      "Score features by Reach, Impact, Confidence, and Effort to see what to build next. Free, no signup, nothing leaves your browser.",
  },
  "feedback-widget-generator": {
    slug: "feedback-widget-generator",
    name: "Feedback Widget Generator",
    tagline: "A copy-paste feedback button for any site",
    description:
      "Generate a lightweight floating feedback button in seconds. No account, no backend, just a script tag you paste into your site.",
  },
  "public-roadmap-template": {
    slug: "public-roadmap-template",
    name: "Public Roadmap Template",
    tagline: "Plan a roadmap people can understand",
    description:
      "Build and copy a clear Now, Next, Later roadmap with status guidance and stakeholder-ready Markdown. Free and private in your browser.",
  },
  "app-name-generator": { slug: "app-name-generator", name: "App Name Generator", tagline: "Find a name for the thing you are building", description: "Generate distinctive app-name ideas from your product category, audience, and tone. Free and private in your browser.", type: "name", fields: [{ label: "What does your app help people do?", placeholder: "e.g. plan meals with friends" }, { label: "Optional style", placeholder: "e.g. playful, technical, calm" }] },
  "feature-name-generator": { slug: "feature-name-generator", name: "Feature Name Generator", tagline: "Turn a feature brief into a clear name", description: "Generate concise, product-ready names for a new feature, setting, workflow, or product area.", type: "name", fields: [{ label: "Describe the feature", placeholder: "e.g. save and reuse report filters" }, { label: "Product tone", placeholder: "e.g. direct and developer-friendly" }] },
  "app-store-description-generator": { slug: "app-store-description-generator", name: "App Store Description Generator", tagline: "Write a clearer app listing", description: "Create an editable app-store description with a hook, benefit-led body copy, and a practical call to action.", type: "copy", fields: [{ label: "What does the app do?", placeholder: "e.g. helps runners follow flexible training plans" }, { label: "Who is it for?", placeholder: "e.g. first-time half marathon runners" }] },
  "value-proposition-generator": { slug: "value-proposition-generator", name: "Value Proposition Generator", tagline: "Say why your product matters", description: "Create focused value-proposition options from a product, audience, and outcome. Useful for homepages and pitch decks.", type: "copy", fields: [{ label: "Product or feature", placeholder: "e.g. embedded product feedback board" }, { label: "Best-fit customer", placeholder: "e.g. small SaaS teams" }] },
  "elevator-pitch-generator": { slug: "elevator-pitch-generator", name: "Elevator Pitch Generator", tagline: "Explain your startup in one breath", description: "Generate short, audience-aware startup pitches for a landing page, demo, investor intro, or community launch.", type: "copy", fields: [{ label: "What are you building?", placeholder: "e.g. a scheduling app for volunteer teams" }, { label: "Who has the problem?", placeholder: "e.g. community organisers" }] },
  "pricing-page-copy-generator": { slug: "pricing-page-copy-generator", name: "Pricing Page Copy Generator", tagline: "Make a plan easier to choose", description: "Draft benefit-led pricing page copy, plan descriptions, and a decision cue without generic marketing fluff.", type: "copy", fields: [{ label: "Product and plan", placeholder: "e.g. feedback tool, Pro plan" }, { label: "What does the customer get?", placeholder: "e.g. unlimited projects and custom branding" }] },
  "product-roadmap-generator": { slug: "product-roadmap-generator", name: "Product Roadmap Generator", tagline: "Turn ideas into Now, Next, Later", description: "Generate a simple outcome-led roadmap structure from your current goal, next bet, and longer-term direction.", type: "template", fields: [{ label: "Current priority", placeholder: "e.g. reduce first-week user drop-off" }, { label: "Next important outcome", placeholder: "e.g. make team collaboration easier" }] },
  "product-launch-checklist": { slug: "product-launch-checklist", name: "Product Launch Checklist", tagline: "Ship without missing the basics", description: "Build a practical launch checklist covering positioning, product readiness, distribution, support, and follow-up.", type: "checklist", fields: [{ label: "What are you launching?", placeholder: "e.g. a new invoicing feature" }, { label: "Who is the first audience?", placeholder: "e.g. existing paying customers" }] },
  "onboarding-checklist-generator": { slug: "onboarding-checklist-generator", name: "Onboarding Checklist Generator", tagline: "Help new users reach value faster", description: "Create a focused first-run onboarding checklist around the user’s first meaningful outcome.", type: "checklist", fields: [{ label: "What outcome should a new user reach?", placeholder: "e.g. publish their first feedback board" }, { label: "Who is onboarding?", placeholder: "e.g. a solo SaaS founder" }] },
  "user-story-generator": { slug: "user-story-generator", name: "User Story Generator", tagline: "Write stories with a real user outcome", description: "Generate a user story, acceptance criteria, edge cases, and questions to resolve before development starts.", type: "template", fields: [{ label: "Feature or job to be done", placeholder: "e.g. let a manager export a monthly report" }, { label: "Primary user", placeholder: "e.g. operations manager" }] },
  "acceptance-criteria-generator": { slug: "acceptance-criteria-generator", name: "Acceptance Criteria Generator", tagline: "Make a feature ready to build", description: "Turn a rough feature description into testable acceptance criteria, edge cases, and a definition of done.", type: "template", fields: [{ label: "Describe the feature", placeholder: "e.g. allow users to invite teammates by email" }, { label: "Important constraint", placeholder: "e.g. invitations expire after seven days" }] },
  "feature-request-template": { slug: "feature-request-template", name: "Feature Request Template", tagline: "Capture requests your team can use", description: "Create a structured feature-request template that asks for the problem, impact, current workaround, and desired outcome.", type: "template", fields: [{ label: "Requested feature", placeholder: "e.g. dark-mode scheduling" }, { label: "Who needs it and why?", placeholder: "e.g. night-shift support teams" }] },
  "bug-report-template": { slug: "bug-report-template", name: "Bug Report Template", tagline: "Turn a vague issue into a useful report", description: "Generate a concise bug-report template with reproduction steps, expected behaviour, actual behaviour, and useful context.", type: "template", fields: [{ label: "What went wrong?", placeholder: "e.g. export button does nothing after selecting a date range" }, { label: "Where did it happen?", placeholder: "e.g. Chrome on macOS" }] },
  "customer-feedback-survey-generator": { slug: "customer-feedback-survey-generator", name: "Customer Feedback Survey Generator", tagline: "Ask questions people will answer", description: "Create a short customer-feedback survey focused on a specific workflow, moment, or product decision.", type: "template", fields: [{ label: "What do you want to learn?", placeholder: "e.g. why trial users do not invite teammates" }, { label: "Who should answer?", placeholder: "e.g. users in their first 14 days" }] },
  "user-interview-question-generator": { slug: "user-interview-question-generator", name: "User Interview Question Generator", tagline: "Run better product conversations", description: "Generate open-ended interview questions that uncover current behaviour, pain, context, and the language customers use.", type: "template", fields: [{ label: "Research topic", placeholder: "e.g. how teams prioritise customer feedback" }, { label: "Interviewee", placeholder: "e.g. product managers at small SaaS companies" }] },
  "user-persona-generator": { slug: "user-persona-generator", name: "User Persona Generator", tagline: "Start with a usable customer hypothesis", description: "Create a lean user persona with goals, constraints, triggers, objections, and questions to validate in research.", type: "template", fields: [{ label: "Audience", placeholder: "e.g. independent app developers" }, { label: "Their main job or problem", placeholder: "e.g. decide what to build from scattered feedback" }] },
  "release-notes-generator": { slug: "release-notes-generator", name: "Release Notes Generator", tagline: "Tell users what changed and why", description: "Draft scannable release notes that explain new capabilities, fixes, and any action users need to take.", type: "copy", fields: [{ label: "What changed?", placeholder: "e.g. added project-level roles and export filters" }, { label: "Why does it matter?", placeholder: "e.g. lets larger teams share reports safely" }] },
  "changelog-generator": { slug: "changelog-generator", name: "Changelog Generator", tagline: "Write an update people will read", description: "Create a concise changelog entry with a clear headline, customer benefit, and natural next step.", type: "copy", fields: [{ label: "Product update", placeholder: "e.g. comments now support image attachments" }, { label: "Customer benefit", placeholder: "e.g. makes bug reports easier to understand" }] },
  "saas-metrics-calculator": { slug: "saas-metrics-calculator", name: "SaaS Metrics Calculator", tagline: "Calculate the numbers behind growth", description: "Calculate simple MRR, annual recurring revenue, gross margin, and monthly churn from a few inputs.", type: "calculator", fields: [{ label: "Monthly recurring revenue", placeholder: "e.g. 12000" }, { label: "Monthly churn percentage", placeholder: "e.g. 3.5" }] },
  "startup-runway-calculator": { slug: "startup-runway-calculator", name: "Startup Runway Calculator", tagline: "Estimate how long your cash lasts", description: "Estimate startup runway from cash in the bank, monthly revenue, and monthly operating costs.", type: "calculator", fields: [{ label: "Cash in the bank", placeholder: "e.g. 80000" }, { label: "Monthly net burn", placeholder: "e.g. 6500" }] },
};
