"use client";

import { useState, type ReactNode } from "react";

function Panel({ children }: { children: ReactNode }) { return <section className="mt-12 rounded-3xl border border-line bg-card p-6 sm:p-8 shadow-soft">{children}</section>; }
function Input({ label, value, setValue, placeholder }: { label: string; value: string; setValue: (value: string) => void; placeholder: string }) { return <label className="block text-sm font-medium text-ink">{label}<textarea value={value} onChange={(e) => setValue(e.target.value)} placeholder={placeholder} rows={3} className="mt-2 w-full resize-none rounded-xl border border-line bg-canvas px-4 py-3 text-sm text-ink placeholder:text-faint outline-none focus:border-clay" /></label>; }
function Result({ value }: { value: string }) { return <div className="mt-7 rounded-2xl border border-line bg-canvas p-5"><button onClick={() => navigator.clipboard.writeText(value)} className="float-right text-sm font-medium text-clay">Copy</button><pre className="whitespace-pre-wrap font-sans text-sm leading-7 text-ink-soft">{value}</pre></div>; }
function words(text: string) { return text.replace(/[^a-zA-Z0-9 ]/g, "").split(/\s+/).filter(Boolean); }

export function AppNameTool() { const [idea, setIdea] = useState(""); const [tone, setTone] = useState(""); const [names, setNames] = useState<string[]>([]); const root = words(idea).map((w) => w[0]?.toUpperCase() + w.slice(1)).join("") || "Nexa"; return <Panel><div className="grid md:grid-cols-2 gap-5"><Input label="What does the app help people do?" value={idea} setValue={setIdea} placeholder="Plan shared meals" /><Input label="What should it feel like?" value={tone} setValue={setTone} placeholder="Warm, simple, modern" /></div><button onClick={() => setNames([`${root}ly`, `${root}Nest`, `${root}Loop`, `Try${root}`, `${root}Signal`, `Orbit${root}`, `${root}Kit`, `${root}Studio`])} className="mt-6 rounded-full bg-clay px-6 py-3 text-sm font-semibold text-white">Generate names →</button>{names.length > 0 && <div className="mt-7 grid sm:grid-cols-2 gap-3">{names.map((name) => <button key={name} onClick={() => navigator.clipboard.writeText(name)} className="rounded-xl border border-line bg-canvas px-4 py-3 text-left font-medium text-ink hover:border-clay">{name}<span className="float-right text-xs text-clay">Copy</span></button>)}</div>}</Panel>; }
export function FeatureNameTool() { const [feature, setFeature] = useState(""); const [names, setNames] = useState<string[]>([]); const root = words(feature).slice(0, 3).map((w) => w[0]?.toUpperCase() + w.slice(1)).join(" ") || "Saved Views"; return <Panel><Input label="What does the feature do?" value={feature} setValue={setFeature} placeholder="Save and reuse report filters" /><button onClick={() => setNames([root, `${root} Hub`, `Smart ${root}`, `${root} Library`, `${root} Controls`, `${root} Workspace`])} className="mt-6 rounded-full bg-clay px-6 py-3 text-sm font-semibold text-white">Generate feature names →</button>{names.length > 0 && <div className="mt-7 grid sm:grid-cols-2 gap-3">{names.map((name) => <p key={name} className="rounded-xl border border-line bg-canvas px-4 py-3 font-medium text-ink">{name}</p>)}</div>}</Panel>; }
function CopyTool({ kind, labels, make }: { kind: string; labels: [string, string]; make: (one: string, two: string) => string }) { const [one, setOne] = useState(""); const [two, setTwo] = useState(""); const [result, setResult] = useState(""); return <Panel><div className="grid md:grid-cols-2 gap-5"><Input label={labels[0]} value={one} setValue={setOne} placeholder="Add a little context" /><Input label={labels[1]} value={two} setValue={setTwo} placeholder="Add a useful detail" /></div><button onClick={() => setResult(make(one || "your product", two || "your customers"))} className="mt-6 rounded-full bg-clay px-6 py-3 text-sm font-semibold text-white">Draft {kind} →</button>{result && <Result value={result} />}</Panel>; }
export const AppStoreTool = () => <CopyTool kind="app-store copy" labels={["What does the app do?", "Who is it for?"]} make={(app, audience) => `A better way for ${audience} to ${app}.\n\nStop stitching together workarounds. ${app} gives you a focused path from the first action to a useful result. Set up in minutes, keep momentum, and make the next step obvious.\n\nBuilt for ${audience}. Download it and get started today.`} />;
export const ValuePropTool = () => <CopyTool kind="value propositions" labels={["What do you offer?", "Who is it for?"]} make={(offer, audience) => `For ${audience} who need to ${offer}, this gives them a simpler way to get the outcome they want—without the usual complexity.\n\nHeadline: ${offer}, without the busywork.\nSupporting line: Built for ${audience} who want a clear next step and a useful result.`} />;
export const ElevatorPitchTool = () => <CopyTool kind="pitch" labels={["What are you building?", "Who has the problem?"]} make={(product, audience) => `${product} is for ${audience}. It replaces the scattered, manual way they handle this job with one focused workflow that gets them to a useful result faster.\n\nOne-line version: ${product} helps ${audience} make progress without the usual friction.`} />;
export const PricingCopyTool = () => <CopyTool kind="pricing copy" labels={["Name the plan or product", "What does the customer get?"]} make={(plan, benefit) => `${plan}\nFor teams ready to make this workflow dependable.\n\nWhat you get\n• ${benefit}\n• A clear path from setup to value\n• Support when the workflow matters\n\nBest for customers who have outgrown workarounds and want to move faster with confidence.`} />;
export const ReleaseNotesTool = () => <CopyTool kind="release notes" labels={["What changed?", "Why does it matter?"]} make={(change, impact) => `## ${change}\n\nYou can now ${change.toLowerCase()}. This means ${impact}.\n\nWhat to do next: try it in your usual workflow and let us know what would make it even better.`} />;
export const ChangelogTool = () => <CopyTool kind="changelog entry" labels={["What shipped?", "What customer benefit does it create?"]} make={(change, benefit) => `### ${change}\n${benefit}.\n\nAvailable now. We built this to remove a common point of friction, so you can spend less time working around the product and more time using it.`} />;
function TemplateTool({ labels, make }: { labels: [string, string]; make: (one: string, two: string) => string }) { const [one, setOne] = useState(""); const [two, setTwo] = useState(""); const [result, setResult] = useState(""); return <Panel><div className="grid md:grid-cols-2 gap-5"><Input label={labels[0]} value={one} setValue={setOne} placeholder="Describe the context" /><Input label={labels[1]} value={two} setValue={setTwo} placeholder="Add a constraint or audience" /></div><button onClick={() => setResult(make(one || "the requested change", two || "the affected user"))} className="mt-6 rounded-full bg-clay px-6 py-3 text-sm font-semibold text-white">Create template →</button>{result && <Result value={result} />}</Panel>; }
export const RoadmapTool = () => <TemplateTool labels={["What must happen now?", "What outcome comes next?"]} make={(now, next) => `# Now, Next, Later\n\n## Now\n${now}\nSuccess looks like: the most important customer outcome is reliably achieved.\n\n## Next\n${next}\nSuccess looks like: the next bottleneck is removed.\n\n## Later\nExplore the opportunities that become valuable once the first two outcomes are true.`} />;
export const UserStoryTool = () => <TemplateTool labels={["What needs to be possible?", "Who needs it?"]} make={(feature, user) => `## User story\nAs a ${user}, I want to ${feature}, so that I can complete the job without a workaround.\n\n## Acceptance criteria\n- The main action is clear and available when needed.\n- A successful outcome is visible.\n- Incomplete input has useful guidance.\n- The primary edge case does not lose work.`} />;
export const AcceptanceTool = () => <TemplateTool labels={["Describe the feature", "Important constraint"]} make={(feature, constraint) => `## ${feature}\n\n### Acceptance criteria\n- A user can complete the primary workflow.\n- The result is saved or confirmed clearly.\n- ${constraint}\n- Errors state what happened and what to do next.\n\n### Definition of done\nThe flow is tested with realistic data, analytics are considered, and support knows how it works.`} />;
export const FeatureRequestTool = () => <TemplateTool labels={["What is being requested?", "Who needs it and why?"]} make={(request, audience) => `# Feature request: ${request}\n\n## Problem\n${audience}\n\n## Desired outcome\nA user can ${request.toLowerCase()} without relying on a workaround.\n\n## Current workaround\nDescribe what people do today and where it breaks down.\n\n## Evidence\nAdd customer quotes, duplicate requests, account impact, and vote count.`} />;
export const BugReportTool = () => <TemplateTool labels={["What went wrong?", "Where did it happen?"]} make={(issue, environment) => `# Bug report\n\n## Summary\n${issue}\n\n## Environment\n${environment}\n\n## Steps to reproduce\n1. Start from a known state.\n2. Complete the action that triggers the issue.\n3. Note the result.\n\n## Expected behaviour\nDescribe the intended result.\n\n## Actual behaviour\nDescribe what happened, including screenshots or errors if available.`} />;
export const SurveyTool = () => <TemplateTool labels={["What do you want to learn?", "Who should answer?"]} make={(goal, audience) => `# Feedback survey for ${audience}\n\n1. Think about the last time you tried to ${goal}. What happened?\n2. What was the hardest or most frustrating part?\n3. What did you do instead?\n4. If one thing changed, what would make the biggest difference?\n5. May we follow up to learn more?`} />;
export const InterviewTool = () => <TemplateTool labels={["Research topic", "Who are you interviewing?"]} make={(topic, audience) => `# Interview guide: ${topic}\n\nFor: ${audience}\n\n- Tell me about the last time this came up.\n- What triggered you to act?\n- Walk me through what you did, step by step.\n- What was difficult, slow, or uncertain?\n- What have you tried before?\n- How would you know a better solution was working?`} />;
export const PersonaTool = () => <TemplateTool labels={["Who is the audience?", "What job are they trying to do?"]} make={(audience, job) => `# Lean persona: ${audience}\n\n## Primary job\n${job}\n\n## Trigger\nWhat changes or frustration makes this job urgent?\n\n## Constraints\nTime, budget, confidence, technical skill, and approval requirements.\n\n## Objections\nWhat would stop them from trying a new approach?\n\n## Validate next\nTalk to five people in this group about a recent real example—not a hypothetical.`} />;
function ChecklistTool({ firstLabel, secondLabel, title, items }: { firstLabel: string; secondLabel: string; title: string; items: string[] }) { const [context, setContext] = useState(""); const [audience, setAudience] = useState(""); const [checked, setChecked] = useState<boolean[]>(items.map(() => false)); return <Panel><div className="grid md:grid-cols-2 gap-5"><Input label={firstLabel} value={context} setValue={setContext} placeholder="Add the context" /><Input label={secondLabel} value={audience} setValue={setAudience} placeholder="Add the audience" /></div><div className="mt-7 rounded-2xl border border-line bg-canvas p-5"><h2 className="font-semibold text-ink">{title}{context ? `: ${context}` : ""}</h2><p className="text-sm text-muted mt-1">Audience: {audience || "add an audience above"}</p><div className="mt-5 space-y-3">{items.map((item, index) => <label key={item} className="flex gap-3 text-sm text-ink-soft"><input type="checkbox" checked={checked[index]} onChange={() => setChecked(checked.map((value, i) => i === index ? !value : value))} className="mt-1 accent-clay" />{item}</label>)}</div></div></Panel>; }
export const LaunchTool = () => <ChecklistTool firstLabel="What are you launching?" secondLabel="Who is first?" title="Launch checklist" items={["Confirm the one-sentence promise and call to action.", "Test the primary path and payment or signup flow.", "Prepare screenshots, demo, and short announcement copy.", "Decide who monitors feedback and bugs on launch day.", "Set a one-week review for activation, questions, and requests."]} />;
export const OnboardingTool = () => <ChecklistTool firstLabel="What first outcome should users reach?" secondLabel="Who is onboarding?" title="Onboarding checklist" items={["State the first meaningful outcome in plain language.", "Remove optional setup from the first session.", "Show one next action at a time.", "Confirm success with a visible result.", "Ask for feedback when the user has enough context to answer."]} />;
export function SaaSMetricsTool() { const [mrr, setMrr] = useState(""); const [churn, setChurn] = useState(""); const monthly = Number(mrr.replace(/[^0-9.]/g, "")); const rate = Number(churn.replace(/[^0-9.]/g, "")); return <Panel><div className="grid md:grid-cols-2 gap-5"><Input label="Monthly recurring revenue" value={mrr} setValue={setMrr} placeholder="12000" /><Input label="Monthly churn percentage" value={churn} setValue={setChurn} placeholder="3.5" /></div><div className="mt-7 grid sm:grid-cols-3 gap-4"><Metric label="MRR" value={monthly ? monthly.toLocaleString() : "—"} /><Metric label="ARR" value={monthly ? (monthly * 12).toLocaleString() : "—"} /><Metric label="Revenue retained next month" value={rate ? `${(100 - rate).toFixed(1)}%` : "—"} /></div></Panel>; }
export function RunwayTool() { const [cash, setCash] = useState(""); const [burn, setBurn] = useState(""); const available = Number(cash.replace(/[^0-9.]/g, "")); const monthly = Number(burn.replace(/[^0-9.]/g, "")); return <Panel><div className="grid md:grid-cols-2 gap-5"><Input label="Cash in the bank" value={cash} setValue={setCash} placeholder="80000" /><Input label="Monthly net burn" value={burn} setValue={setBurn} placeholder="6500" /></div><div className="mt-7 rounded-2xl border border-line bg-canvas p-6"><p className="text-sm text-muted">Estimated runway</p><p className="font-serif text-5xl text-ink mt-2">{available && monthly ? `${(available / monthly).toFixed(1)} months` : "—"}</p><p className="text-sm text-muted mt-3">Recalculate after material changes in revenue, hiring, or operating costs.</p></div></Panel>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-line bg-canvas p-4"><p className="text-xs text-muted">{label}</p><p className="font-serif text-2xl text-ink mt-1">{value}</p></div>; }
