import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Nav } from "@/components/marketing/Nav";
import { Footer } from "@/components/marketing/Footer";
import { JsonLd } from "@/components/JsonLd";
import { GUIDES } from "../data";

export function generateStaticParams() { return Object.keys(GUIDES).map((slug) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const g = GUIDES[(await params).slug]; if (!g) return {}; return { title: g.title, description: g.description, alternates: { canonical: `/guides/${g.slug}` }, openGraph: { title: g.title, description: g.description, url: `/guides/${g.slug}` } }; }

export default async function Page({ params }: { params: Promise<{ slug: string }> }) { const g = GUIDES[(await params).slug]; if (!g) notFound(); const ld = { "@context": "https://schema.org", "@type": "TechArticle", headline: g.title, description: g.description, author: { "@type": "Organization", name: "Upstep" } }; return <div className="min-h-screen bg-canvas"><JsonLd data={ld} /><Nav /><main className="max-w-3xl mx-auto px-6 py-16"><nav className="text-xs text-faint mb-8"><Link href="/guides">Guides</Link><span className="mx-2">/</span>{g.category}</nav><span className="text-xs font-semibold uppercase tracking-wide text-clay">{g.category} · {g.minutes} minute guide</span><h1 className="font-serif text-4xl sm:text-5xl text-ink mt-3 mb-5 leading-tight">{g.title}</h1><p className="text-lg text-muted leading-relaxed mb-12">{g.description}</p><div className="space-y-12">{g.sections.map((s, i) => <section key={s.title}><div className="flex items-start gap-4"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-clay/10 text-xs font-bold text-clay">{i + 1}</span><div className="min-w-0 flex-1"><h2 className="text-xl font-semibold text-ink">{s.title}</h2><p className="text-sm text-muted leading-relaxed mt-2">{s.body}</p>{s.code && <pre className="mt-4 overflow-x-auto rounded-xl border border-line bg-surface p-4 text-xs text-ink-soft"><code>{s.code}</code></pre>}</div></div></section>)}</div><aside className="mt-16 rounded-2xl border border-clay/20 bg-clay/5 p-8"><h2 className="font-serif text-2xl text-ink">Put the guide into practice</h2><p className="text-sm text-muted mt-2 mb-5">Create an Upstep project, copy its key, and test the integration on the free plan.</p><Link href="/login" className="inline-flex rounded-full bg-clay px-6 py-3 text-sm font-semibold text-white">Get started free →</Link></aside></main><Footer /></div>; }
