import type { Metadata } from "next";
import Link from "next/link";
import { Nav } from "@/components/marketing/Nav";
import { Footer } from "@/components/marketing/Footer";
import { JsonLd } from "@/components/JsonLd";
import { RoadmapBuilder } from "./RoadmapBuilder";

export const metadata: Metadata = { title: "Free Public Roadmap Template — Now, Next, Later", description: "Create a clear Now, Next, Later product roadmap and copy it as Markdown. Free, private, and no signup required.", alternates: { canonical: "/tools/public-roadmap-template" } };

export default function Page() {
  return <div className="min-h-screen bg-canvas"><JsonLd data={{ "@context": "https://schema.org", "@type": "SoftwareApplication", name: "Public Roadmap Template", applicationCategory: "BusinessApplication", offers: { "@type": "Offer", price: "0", priceCurrency: "USD" } }} /><Nav /><main className="max-w-5xl mx-auto px-6 py-16"><nav className="text-xs text-faint mb-8"><Link href="/tools">Tools</Link><span className="mx-2">/</span>Roadmap template</nav><span className="text-xs font-semibold text-clay uppercase tracking-wide">Free tool · no signup</span><h1 className="font-serif text-4xl sm:text-5xl text-ink mt-3 mb-5">Public roadmap template</h1><p className="text-lg text-muted max-w-2xl mb-10">Turn a backlog into a roadmap customers and teammates can scan. Keep commitments honest with broad Now, Next, and Later horizons.</p><RoadmapBuilder /><section className="mt-14 grid md:grid-cols-2 gap-8 text-sm text-muted leading-relaxed"><div><h2 className="font-serif text-2xl text-ink mb-3">Why Now, Next, Later works</h2><p>Dates create false precision when discovery is incomplete. Horizons communicate order and confidence while leaving room to learn from customer feedback.</p></div><div><h2 className="font-serif text-2xl text-ink mb-3">Make it evidence-led</h2><p>Keep each item outcome-focused, publish only work you are comfortable discussing, and review votes before promoting an item. <Link href="/tools/rice-calculator" className="text-clay">Use the RICE calculator</Link> when initiatives need a comparable score.</p></div></section><div className="mt-14 rounded-2xl border border-clay/20 bg-clay/5 p-8 text-center"><h2 className="font-serif text-2xl text-ink">Publish a live roadmap with voting</h2><p className="text-sm text-muted mt-2 mb-5">Upstep turns feedback into a roadmap your users can follow.</p><Link href="/login" className="inline-flex rounded-full bg-clay px-6 py-3 text-sm font-semibold text-white">Create your roadmap →</Link></div></main><Footer /></div>;
}
